ARG HYDRA_VERSION=v26.2.0
FROM oryd/hydra:${HYDRA_VERSION}

COPY hydra.template.yml /etc/config/hydra/hydra.template.yml
COPY --chmod=755 docker/hydra-entrypoint.sh /usr/local/bin/hydra-entrypoint.sh

ENTRYPOINT ["/usr/local/bin/hydra-entrypoint.sh"]
CMD ["serve", "public"]
