ARG HYDRA_VERSION=v26.2.0
FROM oryd/hydra:${HYDRA_VERSION}

COPY hydra.yml /etc/config/hydra/hydra.yml
# CMD ["migrate", "sql", "-e", "--yes", "&&", "serve", "public", "-c", "/etc/config/hydra/hydra.yml"]
CMD ["serve", "public", "-c", "/etc/config/hydra/hydra.yml"]
